/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikummodul1;

import javax.swing.JOptionPane;

/**
 *
 * @author Martin Hara
 */
public class soal1praktikum extends javax.swing.JFrame {

    /**
     * Creates new form soal1praktikum
     */
    public soal1praktikum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        sanggup1 = new javax.swing.JCheckBox();
        sanggup2 = new javax.swing.JCheckBox();
        alamat = new javax.swing.JTextField();
        nohp = new javax.swing.JTextField();
        fakultas = new javax.swing.JComboBox<>();
        prodi = new javax.swing.JComboBox<>();
        lk = new javax.swing.JRadioButton();
        pr = new javax.swing.JRadioButton();
        ukm = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        alasan = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("FORMULIR PENDAFTARAN UKM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("UNIVERSITAS TRUNOJOYO MADURA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, 23));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Jl. Raya Telang,PO BOX 02 Kecamatan Kamal, Bangkalan Jawa Timur 69162");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Telepon: 031-3011146. Fax: 031-3011506");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Martin Hara\\Downloads\\sakera fiks.jpg")); // NOI18N
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 160, 150));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Martin Hara\\Downloads\\UTM_DIKBUDRISTEK2.png")); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("NAMA LENGKAP             :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 3, 143, -1));

        jLabel6.setText("KESANGGUPAN?             :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 30, 143, -1));

        jLabel7.setText("ALAMAT                           :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 57, 143, -1));

        jLabel8.setText("NO HP                              :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 82, 143, -1));

        jLabel9.setText("PROGRAM STUDI            :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 141, 145, -1));

        jLabel10.setText("FAKULTAS                        :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 110, 143, -1));

        jLabel11.setText("JENIS KELAMIN               :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 168, 145, -1));

        jLabel13.setText("ALASAN BEGABUNG     :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 251, 144, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Martin Hara\\Downloads\\Save_1.png")); // NOI18N
        jButton1.setText("SIMPAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        reset.setIcon(new javax.swing.ImageIcon("C:\\Users\\Martin Hara\\Downloads\\Reset.png")); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel2.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 100, -1));

        keluar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Martin Hara\\Downloads\\Shutdown.png")); // NOI18N
        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel2.add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, -1, -1));

        jLabel14.setText("UKM                                 :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 196, 136, -1));

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel2.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 0, 248, -1));

        sanggup1.setText("SANGGUP");
        jPanel2.add(sanggup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 28, -1, -1));

        sanggup2.setText("SANGAT SANGGUP");
        sanggup2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sanggup2ActionPerformed(evt);
            }
        });
        jPanel2.add(sanggup2, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 28, -1, -1));
        jPanel2.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 54, 248, -1));
        jPanel2.add(nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 82, 248, -1));

        fakultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HUKUM", "EKONOMI BISNIS", "PERTANIAN", "TEKNIK", "ILMU SOIAL ILMU BUDAYA", "PENDIDIKAN", "KEISLAMAN" }));
        jPanel2.add(fakultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 110, 248, -1));

        prodi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teknik Informatika", "Sistem Informasi", "Teknik Elektro", "Teknik Mesin", "Teknik Industri", "Agribisnis", "Pendidikan Bahasa dan Sastra Indonesia", "Pendidikan Guru Sekolah Dasar (PGSD)", "Manajemen", "Akuntansi", "Ilmu Hukum", "Ilmu Komunikasi", "Sastra Inggris", "Agroteknologi" }));
        prodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodiActionPerformed(evt);
            }
        });
        jPanel2.add(prodi, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 138, 248, -1));

        buttonGroup1.add(lk);
        lk.setText("LAKI - LAKI");
        jPanel2.add(lk, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 166, -1, -1));

        buttonGroup1.add(pr);
        pr.setText("PEREMPUAN");
        jPanel2.add(pr, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 166, -1, -1));

        ukm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Korps Sukarela PMI", "Capoeira", "Paduan Suara Golden", "Menwa", "Seni Nanggala", "UKM UK3", "UKM B-Sing", "Triple-C", "UKM TARUNA JAYA" }));
        jPanel2.add(ukm, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 193, 249, -1));

        alasan.setColumns(20);
        alasan.setRows(5);
        jScrollPane1.setViewportView(alasan);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 221, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Martin Hara\\Downloads\\sakera_logo-removebg-preview.png")); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, -60, -1, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        int confirmed = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin keluar dari aplikasi?",
                "Konfirmasi Keluar",
                JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            System.exit(0); // Menghentikan program secara normal
        }
    }//GEN-LAST:event_keluarActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void sanggup2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanggup2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sanggup2ActionPerformed

    private void prodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //ini adalah tempat menyimpan variabel /logika 
        String fnama = nama.getText();
        String falamat=alamat.getText();
        String fnohp=nohp.getText();
        String selectedOptions = "";
            if (sanggup1.isSelected()) {
                selectedOptions += "Sanggup \n";
            }
            if (sanggup2.isSelected()) {
                selectedOptions += "Sangat sangggup\n";
            }
        String selectedOptionsfak = (String) fakultas.getSelectedItem();
        String selectedOptionsprodi = (String) prodi.getSelectedItem();
            if (lk.isSelected()) {
                selectedOptions += "Jenis Kelamin : Laki-Laki";
            }
            if (pr.isSelected()) {
                selectedOptions += "Jenis Kelamin : Perempuan";
            }
        String selectedOptionsukm = (String) ukm.getSelectedItem();
        String falasan=alasan.getText();
        //disini adalah penampilannya
        JOptionPane.showConfirmDialog(null, 
                "Nama : "+fnama+"\n"+
                "Kesanggupan : "+selectedOptions+"\n"+
                "Alamat : "+falamat+"\n"+
                "nohp : "+fnohp+"\n"+
                "fakultas : "+selectedOptionsfak+"\n"+
                "Prodi : "+selectedOptionsprodi+"\n"+
                "Pilihan UKM : "+selectedOptionsukm+"\n"+
                "Alamat : "+falasan+"\n"                        
        , "Data Tersimpan", JOptionPane.DEFAULT_OPTION);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        nama.setText("");
        sanggup1.setSelected(false);
        sanggup2.setSelected(false);
        fakultas.setSelectedIndex(0); // Mengatur ulang fakultas ke indeks pertama
        prodi.setSelectedIndex(0); // Mengatur ulang prodi ke indeks pertama
        lk.setSelected(false);
        pr.setSelected(false);
        ukm.setSelectedIndex(0); // Mengatur ulang UKM ke indeks pertama
        alamat.setText("");
        nohp.setText("");
        alasan.setText("");
         
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(soal1praktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(soal1praktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(soal1praktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(soal1praktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new soal1praktikum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JTextArea alasan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> fakultas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JRadioButton lk;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nohp;
    private javax.swing.JRadioButton pr;
    private javax.swing.JComboBox<String> prodi;
    private javax.swing.JButton reset;
    private javax.swing.JCheckBox sanggup1;
    private javax.swing.JCheckBox sanggup2;
    private javax.swing.JComboBox<String> ukm;
    // End of variables declaration//GEN-END:variables
}
